- name: "Install Apache Debian"
  apt: name=apache2 state=installed
  when: ansible_pkg_mgr == 'apt'

- name: "Install Apache Redhat"
  yum: name=httpd state=installed
  when: ansible_pkg_mgr == 'yum'

- name: "Ensure Apache Starts On Boot"
  service: name=httpd enabled=yes

- name: "Create Virtual Host Includes Directories"
  file: state=directory path={{ item }}
  with_items: httpd_include_dirs

- name: "Copy apache config"
  template: src=httpd.conf.j2 dest={{ httpd_conf_dir }}{{ httpd_conf_file }} owner=root mode=0644 backup=yes
  notify: restart apache
